- .gitignore
- config.xml
- package.json
- src/app/app.component.ts
- src/app/app.module.ts
- src/models/defect.ts
- src/pages/atf/atfDetails/atfDetails.ts
- src/pages/testing/testSubmitted/testSubmitted.ts
- src/services/http.service.ts
- src/services/vehicleTest.service.ts
Injected different configurations + Included all the defect details w…hen posting tests
> Injected Configs + Bug fixes

- package.json
Enabling sonar scanner in mobile build
> "Update package.json"

- package-lock.json
- package.json
- test-config/karma.conf.js
This is to allow the test results to be displayed in CVS Jenkins.
> CVSB-5913 - Add Karma Junit Plugin

- fastlane/Fastfile
This is to enable versioning and renaming of the index.html in fast lane
> Merge to Develop

- src/pages/testing/vehicle/vehicle-brakes/vehicle-brakes.html
This PR will be merged into CVSB-6426 and the bug fix can be tested on that branch.
> CVSB-6730 Bugfix avoid breaking UI if techRecord doesn't have fields

- src/pages/testing/test-creation/test-create/test-create.html
- src/pages/testing/test-creation/test-create/test-create.spec.ts
- src/pages/testing/test-creation/test-create/test-create.ts
- src/pages/testing/test-creation/test-review/test-review.html
- src/pages/testing/test-creation/test-review/test-review.spec.ts
- src/pages/testing/test-creation/test-review/test-review.ts
This PR will be merged into CVSB-6426 and the bug fix can be tested on that branch.
> CVSB-6783 Bugfix odometer reader for trailer

- src/pages/testing/vehicle/vehicle-history/vehicle-history.html
- src/pages/testing/vehicle/vehicle-history/vehicle-history.spec.ts
- src/pages/testing/vehicle/vehicle-history/vehicle-history.ts
This PR will be merged into CVSB-6426 and the bug fix can be tested on that branch.
> CVSB-6784 TrailerID does not appear on test history screen

- src/pages/testing/vehicle/vehicle-additional/vehicle-additional.html
This bugfix will be merged into 6426 and tested there.
> CVSB-6727 

- src/assets/app-data/test-types-data/test-types-fields.metadata.ts
- src/pages/testing/test-creation/complete-test/complete-test.html
- src/pages/testing/test-creation/complete-test/complete-test.scss
- src/pages/testing/test-creation/complete-test/complete-test.spec.ts
- src/pages/testing/test-creation/complete-test/complete-test.ts
- src/pages/testing/test-creation/test-create/test-create.spec.ts
- src/pages/testing/test-creation/test-create/test-create.ts
Feature to be merged and tested in CVSB-6426
> CVSB-6301 Roadworthiness test changes for HGV and TRL

- src/pages/testing/vehicle/vehicle-additional/vehicle-additional.html
- src/pages/testing/vehicle/vehicle-additional/vehicle-additional.scss
This bugfix will be merged in CVSB-6426 and tested on that branch
> CVSB-6735 Fix cosmetic issues

- src/pages/testing/vehicle/vehicle-weights/vehicle-weights.html
The bug [7181](https://jira.dvsacloud.uk/browse/CVSB-7181) will be merged and tested on 6426
> CVSB-7181 Bugfix avoid breaking weights page if backend doesn't provide data

- src/app/app.enums.ts
- src/app/app.scss
- src/pages/testing/vehicle/vehicle-additional/vehicle-additional.html
- src/pages/testing/vehicle/vehicle-additional/vehicle-additional.spec.ts
- src/pages/testing/vehicle/vehicle-additional/vehicle-additional.ts
- src/pages/testing/vehicle/vehicle-brakes/vehicle-brakes.html
- src/pages/testing/vehicle/vehicle-brakes/vehicle-brakes.spec.ts
- src/pages/testing/vehicle/vehicle-brakes/vehicle-brakes.ts
- src/pages/testing/vehicle/vehicle-details/vehicle-details.html
- src/pages/testing/vehicle/vehicle-details/vehicle-details.spec.ts
- src/pages/testing/vehicle/vehicle-details/vehicle-details.ts
- src/pages/testing/vehicle/vehicle-history/vehicle-history.html
- src/pages/testing/vehicle/vehicle-history/vehicle-history.spec.ts
- src/pages/testing/vehicle/vehicle-history/vehicle-history.ts
- src/pages/testing/vehicle/vehicle-lookup/vehicle-lookup.ts
- src/pages/testing/vehicle/vehicle-tyres/vehicle-tyres.html
- src/pages/testing/vehicle/vehicle-tyres/vehicle-tyres.spec.ts
- src/pages/testing/vehicle/vehicle-tyres/vehicle-tyres.ts
- src/pages/testing/vehicle/vehicle-weights/vehicle-weights.html
- src/pages/testing/vehicle/vehicle-weights/vehicle-weights.spec.ts
- src/pages/testing/vehicle/vehicle-weights/vehicle-weights.ts
- src/providers/global/http.service.ts
- src/providers/vehicle/vehicle.service.ts
This PR will be merged and tested on 7051 as it depends on that backend feature.
> CVSB-3963 Provisional tech record

- src/pages/testing/test-creation/complete-test/complete-test.html
- src/pages/testing/test-creation/complete-test/complete-test.spec.ts
- src/pages/testing/test-creation/complete-test/complete-test.ts
- src/pages/testing/test-creation/test-review/test-review.ts
- src/providers/test-type/test-type.service.spec.ts
- src/providers/test-type/test-type.service.ts
Bugfix will be merged in 6426 and tested there
> CVSB-7588 Bugfix roadworthiness test from review screen

- src/models/vehicle/tech-record.model.ts
- src/pages/testing/vehicle/vehicle-brakes/vehicle-brakes.html
- src/pages/testing/vehicle/vehicle-brakes/vehicle-brakes.ts
This fix will be merged and tested on [6426](https://jira.dvsacloud.uk/browse/CVSB-6426)
> CVSB-7439 Fix trailer brakes details not displaying per-axle fields

- src/pages/testing/test-creation/test-create/test-create.spec.ts
Added missing unit test for the defined AC.
PR to be merged in 7090
> CVSB-8690 Added missing unit test

- src/models/latest-version.model.ts
- src/providers/global/sync.service.spec.ts
- src/providers/global/sync.service.ts
This is an iteration on 9489. Will be merged and tested there
> CVSB-9853 Added check for version_checking flag

- package-lock.json
update peer deps and bump versions.
https://jira.dvsacloud.uk/browse/CVSB-16672
> CVSB-16663 Npm audit fix

- package.json
> Added audit-level for audit-de

- src/pages/testing/test-creation/test-create/test-create.spec.ts
- src/pages/testing/test-creation/test-create/test-create.ts
Added test result calculation on review button
https://jira.dvsacloud.uk/browse/CVSB-17386
> CVSB-17386 Added test result calculation on review button

- src/providers/global/auth.service.spec.ts
- src/providers/global/auth.service.ts
https://jira.dvsacloud.uk/browse/CVSB-14693
> CVSB-14693 testerID now contains the employeeid field from the token

- src/pages/testing/vehicle/vehicle-history-details/vehicle-history-details.spec.ts
- src/pages/testing/vehicle/vehicle-history-details/vehicle-history-details.ts
prevent the viewing of test history page from crashing when country of registration does not exist'
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-9644)
> fix(cvsb-9644): prevent the viewing of test history page from crashing

- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/providers/interceptors/auth.interceptor.ts
- src/providers/natives/storage.service.spec.ts
- src/providers/natives/storage.service.ts
Added logs for investigating white screen issue
https://jira.dvsacloud.uk/browse/CVSB-17584
> CVSB-17584 Added logs for investigating white screen issue

- src/assets/data-mocks/tech-record-data.mock.ts
- src/pages/testing/vehicle/vehicle-adr-details/vehicle-adr-details.html
- src/pages/testing/vehicle/vehicle-adr-details/vehicle-adr-details.spec.ts
- src/pages/testing/vehicle/vehicle-adr-details/vehicle-adr-details.ts
Fix to display Guidance notes in the app
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-13945)
> fix(cvsb-13945): to display Guidance notes values when available

- sonar-project.properties
- src/pages/testing/test-creation/test-type-details-input/test-type-details-input.spec.ts
- src/pages/testing/vehicle/vehicle-history-details/vehicle-history-details.spec.ts
- src/providers/global/auth.service.spec.ts
- src/providers/global/state-reforming.service.spec.ts
- src/providers/interceptors/auth.interceptor.spec.ts
- src/providers/utils/common-regEXP.spec.ts
- src/providers/utils/rxjs.utils.spec.ts
- test-config/mocks/mocks.utils.ts
https://jira.dvsacloud.uk/browse/CVSB-16016
> feature/CVSB-16016- unit testing - technical Improvement ticket

- .editorconfig
- .gitignore
- .secignore
- README.md
- env
- package-lock.json
- package.json
> [WIP] Added start script to run the app in the emulator

- src/app/app.component.ts
- src/components/signature-popover/signature-popover.ts
- src/pages/signature-pad/signature-pad.ts
- src/pages/test-station/test-station-details/test-station-details.ts
- src/pages/testing/test-creation/test-cancel/test-cancel.ts
- src/pages/testing/test-creation/test-review/test-review.ts
- src/pages/testing/vehicle/vehicle-lookup/multiple-tech-records-selection/multiple-tech-records-selection.ts
- src/pages/testing/vehicle/vehicle-lookup/vehicle-lookup.ts
- src/pages/visit/visit-timeline/visit-timeline.ts
- src/providers/global/auth.service.ts
- src/providers/global/sync.service.ts
- src/providers/interceptors/auth.interceptor.ts
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-15230)
> fix(cvsb-15230): simplified code hoping to resolve white screen appearing

- src/pages/testing/vehicle/vehicle-history-details/vehicle-history-details.html
Added optional chaining for the additionalInformation 
https://jira.dvsacloud.uk/browse/CVSB-15230
> CVSB-15230 Added optional chaining for the additionalInformation object

- src/app/app.component.ts
- src/pages/testing/defects/advisory-details/advisory-details.html
- src/providers/global/sync.service.ts
- src/providers/interceptors/auth.interceptor.ts
- src/providers/natives/storage.service.ts
Adding more logs to support white screen issue
https://jira.dvsacloud.uk/browse/CVSB-17927
> fix(cvsb-17927): adding more logs to support whitescreen issues

- .gitignore
- README.md
- package-lock.json
- package.json
> fix(install): fix start script with sentry config file generated

- src/app/app.component.ts
- src/pages/test-station/test-station-home/test-station-home.spec.ts
- src/pages/test-station/test-station-home/test-station-home.ts
- src/providers/global/app.service.spec.ts
- src/providers/global/app.service.ts
- src/providers/global/sync.service.spec.ts
- src/providers/global/sync.service.ts
trigger reference data api calls when the app start button is clicked
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-18389)
> fix(feature/cvsb-18389): trigger reference data api calls when the app start button is clicked

- README.md
adding further description on in the readme file
> fix(install): update readme file

- src/assets/app-data/test-types-data/test-types-fields.metadata.ts
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-13805)
> fix(cvsb-13805): display PRS button for voluntary IVA/IVA retests

- src/app/app.enums.ts
- src/pages/visit/visit-timeline/visit-timeline.html
- src/pages/visit/visit-timeline/visit-timeline.spec.ts
- src/pages/visit/visit-timeline/visit-timeline.ts
- src/providers/activity/activity.service.ts
[link to ticket number](Activity API call failing when ending a visit already closed in the background)
> Feature/cvsb 18678- Activity API call failing when ending a visit already closed in the background

- src/assets/app-data/test-types-data/test-types-fields.metadata.ts
Added section for free loaded retest
https://jira.dvsacloud.uk/browse/CVSB-17868
> CVSB-17868 fix: added section for free loaded retest

- fastlane/Fastfile
> CVSB-19147 Injecting provisioning  profile at runtime

- src/app/app.enums.ts
- src/pages/confirmation-page/confirmation.ts
As a VSA I want the end test screen to be updated with copy changes
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-13044)
> fix(feature/cvsb-13044): update support text to - contact the Help Desk

- src/pages/signature-pad/signature-pad.ts
- src/pages/test-station/test-station-details/test-station-details.spec.ts
- src/pages/test-station/test-station-details/test-station-details.ts
- src/pages/testing/test-creation/test-cancel/test-cancel.ts
- src/pages/testing/test-creation/test-create/test-create.ts
- src/pages/testing/test-creation/test-review/test-review.ts
- src/pages/testing/vehicle/vehicle-lookup/multiple-tech-records-selection/multiple-tech-records-selection.spec.ts
- src/pages/testing/vehicle/vehicle-lookup/multiple-tech-records-selection/multiple-tech-records-selection.ts
- src/pages/testing/vehicle/vehicle-lookup/vehicle-lookup.spec.ts
- src/pages/testing/vehicle/vehicle-lookup/vehicle-lookup.ts
- src/pages/visit/visit-timeline/visit-timeline.spec.ts
- src/pages/visit/visit-timeline/visit-timeline.ts
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-19531)
> fix(feature/cvsb 19531): Fix to allow expected error report for google analystics

- env
- scripts/config/application.hybrid.ts
Remove Signature Bucket hard coded
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-19570)
> fix(feature/cvsb-19570): fix to remove signature bucket hard coded

- env
- scripts/config/application.hybrid.ts
Reverts dvsa/cvs-app-mobile#424
> Revert "fix(feature/cvsb-19570): fix to remove signature bucket hard coded"

- src/pages/testing/defects/defect-details/defect-details.ts
Reverts dvsa/cvs-app-mobile#431
> Revert "fix(cvsb-19681): prohibition toggle saved without selecting CTA to save"

- src/pipes/filter-test-type-by-vehicle/filter-test-type-by-vehicle.pipe.spec.ts
- src/providers/auth/authentication/authentication.service.spec.ts
- src/providers/auth/authentication/authentication.service.ts
- src/providers/auth/interceptors-auth/auth-interceptor.spec.ts
- src/providers/auth/interceptors-auth/auth-interceptor.ts
- src/providers/global/http.service.ts
Add network check to isUserAuthenticated & guard to tokenInfo. Fix URL_LATEST_VERSION endpoint returning 400
[https://jira.dvsacloud.uk/browse/CVSB-19687]()
> fix(19687): Auth service network check and URL_LATEST_VERSION endpoint fix

- src/pages/testing/test-creation/test-review/test-review.spec.ts
- src/pages/testing/test-creation/test-review/test-review.ts
- src/pages/testing/vehicle/vehicle-lookup/vehicle-lookup.spec.ts
- src/pages/testing/vehicle/vehicle-lookup/vehicle-lookup.ts
- src/providers/activity/activity.service.spec.ts
- src/providers/activity/activity.service.ts
- src/providers/auth/authentication/auth-model.ts
- src/providers/auth/authentication/authentication.service.spec.ts
- src/providers/auth/authentication/authentication.service.ts
- test-config/services-mocks/authentication-service.mock.ts
- test-config/services-mocks/visit-service.mock.ts
- Adds token expiry check and refresh if required
- Makes open visit check more explicit to avoid false redirects to app home page when visit still open
[CVSB-19907](https://jira.dvsacloud.uk/browse/CVSB-19907) [CVSB-19817](https://jira.dvsacloud.uk/browse/CVSB-19817)
> fix(19907): additional token expiry checks

- src/pages/testing/vehicle/vehicle-details/vehicle-details.ts
- src/providers/test-station/test-station.service.ts
Feature/CVSB-19762 - Investigate Sentry Errors
Investigate and fix top 2 error that occur in sentry in production
**Error 1** - https://sentry.io/organizations/driver-and-vehicle-standards-a/issues/2353714781/?environment=prod&project=5419777&query=is%3Aunresolved&sort=freq&statsPeriod=14d
**Error 2** - https://sentry.io/organizations/driver-and-vehicle-standards-a/issues/2588534809/?environment=prod&project=5419777&query=is%3Aunresolved&sort=freq&statsPeriod=14d
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-19762)
> fix(cvsb-19762): Fix two most common sentry errors

- package.json
Investigate Snyk vulnerabilities
Fix major vulnerabilities in cvs application
https://jira.dvsacloud.uk/browse/CVSB-20006
> feat(20006)

- src/assets/data-mocks/reference-data-mocks/test-types.mock.ts
- src/models/reference-data-models/test-types.model.ts
- src/pages/testing/test-creation/test-types-list/test-types-list.spec.ts
- src/pages/testing/test-creation/test-types-list/test-types-list.ts
- src/providers/utils/common-functions.spec.ts
Feature 13046, 
Make test types consistent across all vehicle types,
https://jira.dvsacloud.uk/browse/CVSB-13046
> feat(13046):pulled original changes into new branch

- src/pages/visit/visit-timeline/visit-timeline.ts
VTA-492 - Remove wait times from app
commented out wait times
[VTA-492](https://jira.dvsacloud.uk/browse/VTA-492)
> feat(feature/vta-492): commented out wait time stuff

- src/providers/test-type/test-type.service.ts
VTA-481 - Unable to finish Test - Prod
Users have been unable to add test types because undefined suggested test type ids were being returned.
[VTA-481](https://jira.dvsacloud.uk/browse/VTA-481)
> feat(feature/vta-481): added catch for undefined suggested test types

- package.json
- src/pages/testing/vehicle/vehicle-lookup/vehicle-lookup.spec.ts
- src/pages/testing/vehicle/vehicle-lookup/vehicle-lookup.ts
- src/providers/visit/visit.service.spec.ts
- src/providers/visit/visit.service.ts
No email provided for test station and space in VRM on vehicle search
[[link to ticket number]()](https://jira.dvsacloud.uk/browse/VTA-516)
> feat(516):tester email

- scripts/config/application.hybrid.ts
> feat(feature/VTA-891): fixed config for feature branches properly
